// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYyR7T_Cov_led4e_nHJLnq2hnzxc9DpA',
    appId: '1:890566733352:web:c94a1dad9b8cebac8b8f1d',
    messagingSenderId: '890566733352',
    projectId: 'flaminqo-ordercoffee',
    authDomain: 'flaminqo-ordercoffee.firebaseapp.com',
    storageBucket: 'flaminqo-ordercoffee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDx_EAG2TGAtP4jBWBmG_hcJ-Rj2pd0tY',
    appId: '1:890566733352:android:7efad74fdf39bb038b8f1d',
    messagingSenderId: '890566733352',
    projectId: 'flaminqo-ordercoffee',
    storageBucket: 'flaminqo-ordercoffee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8YXDGscTid_Jy11Vne3pngIuu_wW8HBs',
    appId: '1:890566733352:ios:6de4658d3b03b1ce8b8f1d',
    messagingSenderId: '890566733352',
    projectId: 'flaminqo-ordercoffee',
    storageBucket: 'flaminqo-ordercoffee.appspot.com',
    iosClientId: '890566733352-7tquoag9oudogb5vtf90afgbupo8kabt.apps.googleusercontent.com',
    iosBundleId: 'com.flaminqo.ordercoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8YXDGscTid_Jy11Vne3pngIuu_wW8HBs',
    appId: '1:890566733352:ios:6de4658d3b03b1ce8b8f1d',
    messagingSenderId: '890566733352',
    projectId: 'flaminqo-ordercoffee',
    storageBucket: 'flaminqo-ordercoffee.appspot.com',
    iosClientId: '890566733352-7tquoag9oudogb5vtf90afgbupo8kabt.apps.googleusercontent.com',
    iosBundleId: 'com.flaminqo.ordercoffee',
  );
}
